# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

jobs:
  simple_tests:
    docker:
      # specify the version you desire here
      - image: circleci/node:carbon
      - image: mongo:3.4.4

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: sudo yarn global add bolt

      - run: bolt

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn lint:eslint --format junit -o reports/junit/js-lint-results.xml

      - run: yarn lint:prettier

      - run:
          name: Unit tests
          command: yarn jest --ci --testResultsProcessor="jest-junit"
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"

      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit

  integration_tests:
    docker:
      - image: circleci/node:carbon
      - image: mongo:3.4.4

    working_directory: /home/circleci/repo

    steps:
      - checkout
      - restore_cache:
          keys:
          - v3-dependencies-{{ checksum "yarn.lock" }}
      - run: sudo apt-get install xvfb libgtk2.0-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2
      - run: sudo yarn global add bolt
      - run:
          name: Bolt - Install packages
          command: CYPRESS_CACHE_FOLDER=$CIRCLE_WORKING_DIRECTORY/node_modules/cypress/.cache/ bolt
      - run:
          name: Starting test project
          command: yarn test:server:start
          environment:
            CLOUDINARY_CLOUD_NAME: $CLOUDINARY_CLOUD_NAME
            CLOUDINARY_KEY: $CLOUDINARY_KEY
            CLOUDINARY_SECRET: $CLOUDINARY_SECRET
      - save_cache:
          paths:
            - node_modules
          key: v3-dependencies-{{ checksum "yarn.lock" }}

      - run:
          name: Running E2E tests
          command: CYPRESS_CACHE_FOLDER=$CIRCLE_WORKING_DIRECTORY/node_modules/cypress/.cache/ yarn cypress:run --reporter junit --reporter-options "mochaFile=reports/junit/cypress-results.xml"

      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots

workflows:
  version: 2
  build:
    jobs:
      - simple_tests
      - integration_tests
